Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:43:28) [MSC v.1934 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> # Preproposal
... 
... ## What idea(s) do you have for your final project?
... 
... #I was thinking about doing a website because I've always wondered how they are developed. I was also thinking of a mathmatical code to give percents on poker hands.
... 
... ## If you plan to collaborate with one or two classmates, what are their names?
... 
... #Nayib Rahman
... 
... ## Do you have any questions of your own?
... 
